repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: debug-statements

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs
        # args: ["-l100"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        exclude: >-
          (?x)^(
            examples/.*\.py$
            | doc/.*\.py$
          )

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        # args: ["-l100"]
