---
version: 2

build:
  os: ubuntu-22.04
  tools:
    # Keep version in sync with tox.ini (docs and gh-actions).
    python: "3.11"

sphinx:
  configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
